name: "godeltaprof: check golang runtime profiler changes"

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  check_go_repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - name: Check golang runtime profiler changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd godeltaprof/compat/cmd/check_golang_profiler_changes && go run main.go \
            -git.user.name="github-actions[bot]" \
            -git.user.email="41898282+github-actions[bot]@users.noreply.github.com"
