name: Check Go repo

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  check_go_repo:
    env:
      GITHUB_TOKEN: ${{ github.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
      - name: Check go repo
        run: make godeltaprof/check_go_repo
